baseURL = "/"
languageCode = "en-us"
title = "Noelita for AISD"
theme = "main"
author = "Koven J. Smith"
summaryLength = 20



[outputs]
  home = ["HTML", "RSS"]


[styles]
  [[styles.colors]]
    primary-color = "#7E9248"
    accent-color = "#4C97B1"
    accent2-color = "rgb(227, 82, 24)"
    darkgrey-color = "#4c4c4c"
    lightgrey-color = "#bfbfbf"
    white-color = "#fbfbfb"

[taxonomies]
  tag = "tags"
  category = "categories"




  # Main menu

  [[menu.main]]
    name = "About"
    url = "/pages/about"
    weight = 25
  [[menu.main]]
    name = "Issues"
    url = "/pages/values"
    weight = 50
  [[menu.main]]
    name = "Events"
    url = "/events"
    weight = 100
  [[menu.main]]
    name = "Get Involved"
    url = "/pages/getinvolved"
    weight = 150

[languages]
  [languages.en]
  	languageName = "English"
  	weight = 1
  [languages.es]
  	languageName = "Español"
  	weight = 2
    title = "Noelita Para AISD"
    [[languages.es.menu.main]]
      name = "Biografía"
      url = "/pages/about"
      weight = 25
    [[languages.es.menu.main]]
      name = "Asuntos"
      url = "/pages/values"
      weight = 50
    [[languages.es.menu.main]]
      name = "Eventos"
      url = "/events"
      weight = 100
    [[languages.es.menu.main]]
      url    = "/pages/getinvolved"
      name   = "Participar"
      weight = 150
