baseURL = "/"
languageCode = "en-us"
title = "Noelita for AISD"
theme = "secondary"
author = "Koven J. Smith"
summaryLength = 20
logo = "/noelita_logo.png"



[outputs]
  home = ["HTML", "RSS"]

[params]


    primary_color = "#0c81bb"
    accent_color = "#eeb226"
    accent2_color = "#5f455e"
    darkgrey_color = "#062728"
    lightgrey_color = "#bfbfbf"
    white_color = "#f0f1f5"

[taxonomies]
  tag = "tags"
  category = "categories"




  # Main menu

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 25
  [[menu.main]]
    name = "Platform & Values"
    url = "/platform"
    weight = 50
  [[menu.main]]
    name = "Events"
    url = "/events"
    weight = 100
  [[menu.main]]
    name = "Get Involved"
    url = "/pages/getinvolved"
    weight = 150

[languages]
  [languages.en]
  	languageName = "English"
  	weight = 1
  [languages.es]
  	languageName = "Español"
  	weight = 2
    title = "Noelita Para AISD"
    [[languages.es.menu.main]]
      name = "Biografía"
      url = "/about"
      weight = 25
    [[languages.es.menu.main]]
      name = "Plataforma y Valores"
      url = "/platform"
      weight = 50
    [[languages.es.menu.main]]
      name = "Eventos"
      url = "/events"
      weight = 100
    [[languages.es.menu.main]]
      url    = "/pages/getinvolved"
      name   = "Participar"
      weight = 150
