baseURL = ""
languageCode = "en-us"
title = "Noelita for AISD"
theme = "secondary"
author = "Koven J. Smith"
summaryLength = 20
logo = "/noelita_logo.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[outputs]
  home = ["HTML", "RSS"]

[params]


    primary_color = "#0c81bb"
    accent_color = "#eeb226"
    accent2_color = "#6d2e46"
    darkgrey_color = "#062728"
    lightgrey_color = "#bfbfbf"
    white_color = "#f0f1f5"
    forestryid = "nfkkwqzqof4"
    analyticsid = "UA-177902406-1"

[taxonomies]
  tag = "tags"
  category = "categories"




  # Main menu

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 25
  [[menu.main]]
    name = "Platform"
    url = "/platform"
    weight = 50
  [[menu.main]]
    name = "Endorsements"
    url = "/about/supporters"
    weight = 75
  [[menu.main]]
    name = "Get Involved"
    url = "/volunteer"
    weight = 125
  [[menu.main]]
    name = "Contact"
    url = "/about/contact"
    weight = 135
  [[menu.main]]
    name = "Donate"
    url = "/donate"
    weight = 150

[languages]
  [languages.en]
  	languageName = "English"
  	weight = 1
  [languages.es]
  	languageName = "Español"
  	weight = 2
    title = "Noelita Para AISD"
    [[languages.es.menu.main]]
      name = "Biografía"
      url = "/about"
      weight = 25
    [[languages.es.menu.main]]
      name = "Plataforma"
      url = "/platform"
      weight = 50
    [[languages.es.menu.main]]
      name = "Endosos"
      url = "/about/supporters"
      weight = 75
    [[languages.es.menu.main]]
      name = "Involúcrate"
      url = "/volunteer"
      weight = 100
    [[languages.es.menu.main]]
        name = "Contactarnos"
        url = "/about/contact"
        weight = 135
    [[languages.es.menu.main]]
      name = "Donar"
      url = "/donate"
      weight = 150
