author = "Koven J. Smith"
baseURL = "https://noelitaforaisd.com"
env = ""
languageCode = "en-us"
logo = "/noelita_logo.png"
summaryLength = 20
theme = "bulma"
title = "Noelita for AISD"
[languages.en]
languageName = "English"
shortName = "en"
weight = 1
[languages.es]
languageName = "Español"
shortName = "es"
title = "Noelita Para AISD"
weight = 2
[[languages.es.menu.main]]
name = "Biografía"
url = "/about"
weight = 25
[[languages.es.menu.main]]
name = "Plataforma"
url = "/platform"
weight = 50
[[languages.es.menu.main]]
name = "Endosos"
url = "/about/supporters"
weight = 75
[[languages.es.menu.main]]
name = "Contactarnos"
url = "/about/contact"
weight = 135
[[languages.es.menu.secondary]]
name = "Involúcrate"
url = "/volunteer"
weight = 100
[[languages.es.menu.secondary]]
name = "Donar"
url = "/donate"
weight = 150
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact"
url = "/about/contact"
weight = 4
[[menu.main]]
name = "Endorsements"
url = "/about/supporters"
weight = 3
[[menu.main]]
name = "Platform"
url = "/platform"
weight = 2
[[menu.main]]
name = "About"
url = "/about"
weight = 1
[[menu.secondary]]
name = "Get Involved"
url = "/volunteer"
weight = 1
[outputs]
home = ["HTML", "RSS"]
[params]
accent2_color = "#6d2e46"
accent_color = "#eeb226"
analyticsid = "UA-177902406-1"
darkgrey_color = "#062728"
env = "production"
forestryid = "nfkkwqzqof4"
lightgrey_color = "#bfbfbf"
primary_color = "#0c81bb"
white_color = "#f0f1f5"
[taxonomies]
category = "categories"
tag = "tags"
